### ISSUE TITLE
VM Recoomendations

### ISSUE THREAD

**Issue by gergelytakacs** [fei-stu-drones/lrs#1]
Could you guys possibly provide some info for the recommended specs of running AirSim in a VM environment? Also I'd ask @annavargova to report her experiences with VM/AirSim.

(Also, I'm the first one to put an issue up, haha;)

**Comment by fei-stu-drones** [comment]
@gergelytakacs We **would not recommend** running AirSim inside a VM environment. We also see no reason to do that, since AirSim can natively run on Windows, Mac (I think you have to build it on mac) and Linux. 

Other than that - you need exactly the same specs as for any gaming PC since it is based on Unreal Engine - same as a lot of modern PC games. So any Nvidia mid to high-end GPU (RTX 30xx series) and the same with the CPU. It is also heavily dependant on the exact AirSim environment (map) that you are using - if there are many moving objects with many moving parts, it is of course much more demanding.

**Comment by gergelytakacs** [comment]
Thanks for the reply, duly noted. Will try to get frustrated with VM/Win version due to the inflexibility of my current setup (work laptop) but I'll try to move to a Linux rig. Our current machines are not up to the expectations of running a game-like environment, so will be actually interesting to see what even works here. (My laptop doesn't even have built-in graphics, not a gamer and hasn't needed so far).

**In any case, your recommendation(s) on emulation / HW specs would be nice in the base readme for students.** In the meantime I might just see for the heck of it what can I do in a VM/Win version - out of curiousity.

**Comment by gergelytakacs** [comment]
@fei-stu-drones  Oh yeah. This whole adventure with VM was a fail. ;)  As I see the rest of the requisites, I'd rather shoot myself in the knee than do it in Windows. Oh well. Off to set up a true (non-VM) Linux rig... Also, as we haven't used 3D for anything, we are finding out that our HW is not really up to the task.

**Comment by fei-stu-drones** [comment]
@gergelytakacs One student set it up with [WSL - Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/), which might be the way. He had some issues with it, but in general it at least partially, worked. You ran ROS and ArduPilot in WSL and AirSim natively on Windows. Maybe I can ask him to write a small tutorial for that.

**Comment by gergelytakacs** [comment]
@fei-stu-drones The tutorial can't hurt, but I think we'll need to go the Linux way anyways!
